apiVersion: v1
data:
  secretkey: OU9pTGVIU1hsclRIWU5xcCtRT2xYbVZZSEdaN05tVHFYVWVxODY5ZnN3bTNCb0svM1ZMQ1JiZUFMMEc3MjVlTgpaUHIzS0I4OFZUNzYxZzdieE1UQmxTdUlnUkFGTmU5VHp1QWpQTzZ2Y3lXTnNRT3BKc1gvaSt2YmR6NCtWdlN4Ck15VDBZVklBa1BqZFo2QWozY2FvazRnTUoxR1ZHL0VmWHB5NmQweXhnWGc9
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
type: Opaque
